modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]] # TerraFirmaCraft
modId = "tfc"
mandatory = true
versionRange = "[3.2.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]] # Untamed Wilds
modId = "untamedwilds"
mandatory = true
versionRange = "[4.0.4,)"
ordering = "NONE"
side = "BOTH"
